### ISSUE TITLE
4.3 branch

### ISSUE THREAD

**Issue by skynet** [johnpbloch/wordpress#10]
There's a 4.3 RC already. Did you ever get to sync these?

https://wordpress.org/news/2015/07/wordpress-4-3-release-candidate/

tx,

**Comment by swissspidy** [comment]
As beta releases and RC's in WordPress aren't specifically tagged or anything (just ordinary ZIP files), you can only use the `4.x-dev` versions as these are based on the Subversion branches. The content is the same.
