### ISSUE TITLE
Add languages

### ISSUE THREAD

**Issue by artursopelnik** [johnpbloch/wordpress#12]
Could you add languages - https://translate.wordpress.org/

**Comment by johnpbloch** [comment]
This is out of the scope of a core package. I recall somebody had done some work to make independent packages for each language pack, but I cannot recall who it was or where to find their work. I'll see what I can find and let you know.

**Comment by johnpbloch** [comment]
@artursopelnik It was http://languages.koodimonni.fi/

**Comment by artursopelnik** [comment]
@johnpbloch coool :+1:
