### ISSUE TITLE
Avoid installing default themes

### ISSUE THREAD

**Issue by khromov** [johnpbloch/wordpress#14]
Is there any way to get rid of the default "Twenty" themes that are included when the Composer package gets installed?

**Comment by johnpbloch** [comment]
This isn't something we're going to do in this repository at the moment. It would be something worth considering for [when I split out a new core package with no dependencies](https://code.johnpbloch.com/2015/07/upcoming-changes-to-my-wordpress-fork/), though.

**Comment by khromov** [comment]
@johnpbloch Sounds like a good way forward. The reason I started this issue is because you typically have to update themes independently, and it'd be nice to do it with WPackagist. Right now you end up having to move `wp-content/themes` to avoid not being able to update the default themes without a core update.

**Comment by christianzt19** [comment]
+1

**Comment by khromov** [comment]
Any movement on this? Installing the `johnpbloch/wordpress` now forces you to also install 6 additional themes. (Twenty-eleven to Twenty-sixteen) :cry:

**Comment by puredazzle** [comment]
+1

**Comment by mickenorlen** [comment]
+1

**Comment by coreyworrell** [comment]
Any updates on this @johnpbloch ?
