### ISSUE TITLE
Method for automating this repo

### ISSUE THREAD

**Issue by joshdaws** [johnpbloch/wordpress#15]
Can you post your method of automating this repo somewhere? My company is nervous about using this as a dependency so I'd like to explore managing our own automated repo.

**Comment by johnpbloch** [comment]
I'm not entirely sure why you wouldn't feel nervous using my automation code if you're nervous about using the code it produces.

The automation is not available for general release for a few various reasons and I'm disinclined to change that policy.

**Comment by joshdaws** [comment]
Because a security release has been released and your automation code hasn't picked it up. :-/
