### ISSUE TITLE
Auto update Packagist 

### ISSUE THREAD

**Issue by timbofield** [johnpbloch/wordpress#18]
Could you setup an auto update for the packgist account 
https://packagist.org/packages/johnpbloch/wordpress 

Seems this isn't in place currently as 4.4.2 is still not available via packagist. Should be possible to have packagist update on commit to this repo.

Thanks

**Comment by johnpbloch** [comment]
Auto update was already set up. Not really sure if Packagist or Github was to blame, but I went ahead and did a manual update.
