### ISSUE TITLE
WP 4.6 beta 2

### ISSUE THREAD

**Issue by craigedmunds** [johnpbloch/wordpress#21]
Hi John, we use your distribution via trellis, wondered if you're intending to support the beta channel, i.e. https://wordpress.org/news/2016/07/wordpress-4-6-beta-2/?

**Comment by swissspidy** [comment]
As beta releases in WordPress aren't specifically tagged or anything (just ordinary ZIP files), you can only use the `4.x-dev` versions as these are based on the Subversion branches.

**Comment by johnpbloch** [comment]
@craigedmunds This repository doesn't receive pre-release tags, but the [wordpress-core](https://github.com/johnpbloch/wordpress-core) does now. You can already check it out over there with 4.8 betas and release candidates.
