### ISSUE TITLE
4.7.3 missing from https://packagist.org/packages/johnpbloch/wordpress

### ISSUE THREAD

**Issue by archon810** [johnpbloch/wordpress#27]
Hi,

How often does Packagist refresh https://packagist.org/packages/johnpbloch/wordpress? 4.7.3 has been live for 2 hours now. Is there a way to trigger a refresh on Packagist by any of us users?

Thanks.

**Comment by archon810** [comment]
OK, it's there now. If there's any way to speed this up in the future, that'd be great. Security updates are very important for WP.

**Comment by archon810** [comment]
Same thing happening with 4.7.4. https://wordpress.org/news/2017/04/wordpress-4-7-4/ released over an hour ago.

**Comment by johnpbloch** [comment]
The core team hasn't tagged the release in svn yet: http://develop.svn.wordpress.org/tags/

**Comment by johnpbloch** [comment]
and of course, as soon as i say that, they did. 🙄
