### ISSUE TITLE
4.6.6, 4.5.9 etc have erroneous dependencies

### ISSUE THREAD

**Issue by jnweaver** [johnpbloch/wordpress#33]
All of the older (older than 4.7.x) versions of this latest May 16, 2017 patch release of WP core, have composer dependencies for `"johnpbloch/wordpres-core": "4.6.x-dev"`, `"johnpbloch/wordpres-core": "4.5.x-dev"`, etc.

These are in addition to the correct wordpress-core dependencies (e.g. `"johnpbloch/wordpress-core": "4.6.6"`

It results in composer errors such as:

```
    - Installation request for johnpbloch/wordpress 4.6.6 -> satisfiable by johnpbloch/wordpress[4.6.6].
    - johnpbloch/wordpress 4.6.6 requires johnpbloch/wordpres-core 4.6.x-dev -> no matching package found.
```

**Comment by royduin** [comment]
Same issue here...

**Comment by JohNan** [comment]
Same issue with latest 3.9.19

```
  Problem 1
    - Installation request for johnpbloch/wordpress 3.9.19 -> satisfiable by johnpbloch/wordpress[3.9.19].
    - johnpbloch/wordpress 3.9.19 requires johnpbloch/wordpres-core 3.9.x-dev -> no matching package found.
```

**Comment by djvdorp** [comment]
+1

**Comment by johnpbloch** [comment]
This has been fixed and `*.1` releases for all of the latest versions on the `3.7`-`4.6` branches have been pushed up (e.g. `4.6.6.1`, etc.).

**Comment by royduin** [comment]
Awesome! Thanks!

**Comment by jnweaver** [comment]
Thank you!
