### ISSUE TITLE
Path for autoload.php

### ISSUE THREAD

**Issue by Johnsontylk** [johnpbloch/wordpress#36]
Hi, 

I am having an issue with autoload.php path from other files after some changes with the new wp directory. Is there I nice clean solution to make sure a file loads autoload.php wp-config.php. 
Where the root directory for NGINX is lower then the top level. 

Example
app1.domain.com - Root Directory is Folder1
Top Level -> Folder1 -> Folder2 -> File (includes autoload.php and wp-config.php)

app2.domain.com - Root Directory is wp
Top Level - wp
Top Level -> Vendor - autoload.php

**Comment by johnpbloch** [comment]
I'm not sure what's being asked here, but this doesn't seem to be related to this package specifically.
