### ISSUE TITLE
Where is the 5.0.5 release?

### ISSUE THREAD

**Issue by royduin** [johnpbloch/wordpress#41]
The release is listed here: https://github.com/WordPress/WordPress/releases

**Comment by johnpbloch** [comment]
Not sure why, but the core team didn't see fit to release it here: https://wordpress.org/download/releases/

**Comment by johnpbloch** [comment]
Huh. https://github.com/WordPress/WordPress/compare/88852fe...d610356 doesn't look like there's anything to release in 5.0.5? I'm a little confused here.

**Comment by johnpbloch** [comment]
Sorry to bother you @pento. Since you're the author of the above commit, can you shed some light on the 5.0.5 release and why it's not on the .org download page/why it's the same as 5.0.4 in the github mirror?

**Comment by pento** [comment]
5.0.5 was an accident. :)

I tagged 5.0.5 when I meant to tag 5.0.4. Systems haven't had a chance to delete the tag yet, because it's kind of fiddly to do. We may just skip 5.0.5 and go to 5.0.6 when the next 5.0.x release happens.

**Comment by royduin** [comment]
Lol, thanks for the clarification @pento 👍
