### ISSUE TITLE
johnpbloch/wordpress 5.2.1 requires php 5.3.2 -> your PHP version (7.2.16) does not satisfy that requirement

### ISSUE THREAD

**Issue by archon810** [johnpbloch/wordpress#44]
Hi,

Trying to update to 5.2.1 today, and getting this issue:

```
Problem 1
    - Installation request for johnpbloch/wordpress 5.2.1 -> satisfiable by johnpbloch/wordpress[5.2.1].
    - johnpbloch/wordpress 5.2.1 requires php 5.3.2 -> your PHP version (7.2.16) does not satisfy that requirement.
```

Any idea why?

Thanks.

**Comment by archon810** [comment]
How did this happen? I see the problem.

5.2.0: https://packagist.org/packages/johnpbloch/wordpress#5.2.0
```
requires

php: >=5.3.2
```

5.2.1: https://packagist.org/packages/johnpbloch/wordpress#5.2.1 

```requires

php: 5.3.2
```

**Comment by johnpbloch** [comment]
@archon810 Thanks for bringing this to my attention. As a temporary workaround, you can change the dependency to `johnpbloch/wordpress:5.2.x-dev`, as it's not affected by this problem. I'll be pushing out updates soon, but this is a result of [the build script](https://github.com/johnpbloch/build-wp/blob/master/build-wp.sh#L202) not including the `>=` for this repo.

**Comment by szepeviktor** [comment]
@johnpbloch Could you move the 5.2.1 tag?

**Comment by szepeviktor** [comment]
```
$ composer require johnpbloch/wordpress:5.2.x-dev
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for johnpbloch/wordpress 5.2.x-dev -> satisfiable by johnpbloch/wordpress[5.2.x-dev].
    - johnpbloch/wordpress 5.2.x-dev requires johnpbloch/wordpress-core 5.2.x-dev -> satisfiable by johnpbloch/wordpress-core[5.2.x-dev] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

**Comment by rfair404** [comment]
I too am having this issue. 
```
  Problem 1
    - Installation request for johnpbloch/wordpress 5.2.1 -> satisfiable by johnpbloch/wordpress[5.2.1].
    - johnpbloch/wordpress 5.2.1 requires php 5.3.2 -> your PHP version (7.1.23) does not satisfy that requirement.
```

**Comment by kraftner** [comment]
@szepeviktor I guess the issue for you is [`minimum-stability`](https://getcomposer.org/doc/04-schema.md#minimum-stability) in your root `composer.json` since you're trying to install a dev dependency.

**Comment by szepeviktor** [comment]
@kraftner Thanks.

> ./composer.json has been created

I am trying without an existing composer.json.

**Comment by Rarst** [comment]
A quick override without package change `composer update --no-dev --ignore-platform-req`

PS btw PHP 5.3.2 is _also_ outdated on WP 5.2.*, should be >=5.6.20

**Comment by ihorvorotnov** [comment]
> A quick override without package change `composer update --no-dev --ignore-platform-req`

Great tip, completely forgot about it! 
Although it's `--ignore-platform-reqs` (ends with s, plural form) :)

**Comment by johnpbloch** [comment]
Ok, sorry for the delay here. I just pushed a commit that sets php requirements for 5.2.1 to the correct `>=5.6.20` and update the 5.2.1 tag to point to the updated commit. Composer update and install procedures should work as expected without work-arounds going forward. The underlying cause has been addressed in the build repo, so it won't be re-appearing.

**Comment by johnpbloch** [comment]
(I should also note that I had to go into packagist and manually update the repo, so there might be some delay getting the updated manifest into your pipelines.)
