### ISSUE TITLE
[Media upload fails] Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.

### ISSUE THREAD

**Issue by thaodc** [johnpbloch/wordpress#50]
Hi everybody,

I have one issue when trying to upload media file to Azure cloud and I got the error message below:

```
Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.
```

If I turn on the Azure plugin option `Keep local files` then it work fine, but if I turn off that option then always got the error message above

![Screenshot (73)](https://user-images.githubusercontent.com/14971147/90591983-a3939880-e20e-11ea-9212-b06639fce50e.png)

Info:
PHP 7.4.6
Wordpress 5.4.0
Azure plugin: https://plugins.svn.wordpress.org/windows-azure-storage/tags/4.3.1

Does anyone have same problem with me?

Thanks!

**Comment by johnpbloch** [comment]
Hi @thaodc thanks for coming by! This appears to be unrelated to this repository. I'd suggest looking into the Windows Azure Storage plugin's support forums: https://wordpress.org/support/plugin/windows-azure-storage/
