### ISSUE TITLE
Release candidates of 4.2 branch

### ISSUE THREAD

**Issue by salaros** [johnpbloch/wordpress#6]
Please add 4.2 branch, I know it is still being developed and its release was delayed, but still some people would love to switch to 4.2 RC4 and use some of its features (for example [conditional javascript tags](https://core.trac.wordpress.org/ticket/16024) )

**Comment by johnpbloch** [comment]
The repo is completely automated in it's updates, so without a `/branches/4.2` directory upstream, I won't be adding one manually, lest I mess automation up.

I think we can get the same effect, though, by automatically adding the next release's dev branch as an alias to the master branch. During the release cycle, e.g. this one being for 4.2, `4.2.x-dev` would alias to `dev-master`. Once there's a 4.2 branch in SVN, we'd remove the alias from master and let the branch take `4.2.x-dev` over and master would re-alias itself to 4.3.x-dev.

How does that sound?

**Comment by johnpbloch** [comment]
And it looks like core branched today, so your specific need for a 4.2 dev branch is met. Still, it'd probably be a good idea to add some logic to alias the current dev branch to master until the actual branch is created.

**Comment by blueliquiddesigns** [comment]
+1 for aliasing the current dev branch to master so we can easily test beta and RC versions of WordPress.
